services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env 
    volumes:
      - .:/app
      - /app/node_modules

    restart: unless-stopped

networks:
  default:
    external: true
    name: desafio-network